color: #BD0000;  /*  DEEP RED PRICE COLOR */

#F2F2F2; /* OFF WHITE FOOTER BKGD */

 color: #041c64;  /* DARK BLUE FOOTER MENU TEXT */

 /* #F2F2F2;  OFF WHITE BKG */

 #0a40e2; /*  MEDIUM BLUE BUTTON */

 #007ebc; /* LIGHTER SHADE MEDIUM BLUE*/ #6c8ef6; WORKS BETTER

#fe888b; /* LIGHT ROSE DESCRIPTION/ADDITIONAL TABS */

#3E96B9;  /* blue ends of banner */

#BDCCFB;  /* pastel blue breadcrumbs */